### ISSUE TITLE
“Current” builds are unavailable in xUbuntu_19.10 

### ISSUE THREAD

**Issue by notpushkin** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#31]
```
ale@ale-ThinkPad-T420:~$ sudo apt-get install waterfox-current-kpe
[sudo] password for ale: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package waterfox-current-kpe
```

On https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_19.10/amd64/, there's no package for `waterfox-current-*` as well. I was able to grab one [here](https://software.opensuse.org//download.html?project=home%3Ahawkeye116477%3Awaterfox&package=waterfox-current-kpe), but it's not obvious so perhaps you could point it out (or enable it back in the repo)? Thank you!

**Comment by hawkeye116477** [comment]
`On https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_19.10/amd64/, there's no package for waterfox-current-* as well.`

Hmm, I see it...

**Comment by notpushkin** [comment]
Hmmmm now I can see it too, and after another `apt update` it gets resolved by APT as well. Weird. Thanks!
