### ISSUE TITLE
Remove Debian package language-pack prompt?

### ISSUE THREAD

**Issue by jursed** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#32]
This is just a suggestion, but would you consider removing the language pack prompt in the Debian packages? 

With every single Waterfox update, the info about the language pack pops up and holds up the rest of the installation until manually confirmed. For people who prefer to run apt/dpkg without non-interactive flags (`--assume-yes`, `--assume-no`), that is pretty annoying. :)

(The reason for running interactive updates is that oftentimes, important system packages ask about overwriting config files, so it makes sense to choose the response to those prompts individually.)

Wouldn't it be sufficient to just have this information in the README, as is already the case?

Other than that, keep up the great work, Waterfox is fantastic :+1:

**Comment by hawkeye116477** [comment]
Maybe not everyone reads on readme. Anyone, I'll think about this.
