### ISSUE TITLE
32bit appimage?

### ISSUE THREAD

**Issue by pirate486743186** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#33]
can you please make a 32bit appimage.
Assuming it still compiles. I know that they are no assurances that it will be any good.

**Comment by hawkeye116477** [comment]
I tried in the past to do 32-bit package, but there were problems with compiling it, so gave up.
Also problem might be that I'll probably need to use Fedora 30, cuz CentOS 7 doesn't has 32-bit image, so compatibility might be much worse (glibc 2.29).
I didn't suppose that someone still has 32-bit OS. If you want Waterfox Classic, then rather low chances, probably easier would be to compile Waterfox Current. Maybe someday I'll return to this and I'll see what could be done if you want Current, but I didn't promise anything.

**Comment by pirate486743186** [comment]
i have an old 32bit laptop with ubuntu 18.04.

So, you are saying, that it doesn't just compile any more.... I'll survive with the distributions browser.

**Comment by hawkeye116477** [comment]
> it doesn't just compile any more.

Yeah, there were many errors when I tried with clang, probably some patches would be needed. In case of GCC as I remember I always had problems with memory, it complained that it needs more RAM.

> old 32bit laptop with ubuntu 18.04

Ubuntu 18.04 has glibc 2.27, so it might be a problem. You'll need to update to Focal.

**Comment by hawkeye116477** [comment]
Small update, there is different problem, tools for making AppImages (https://build.opensuse.org/project/show/OBS:AppImage) are only for openSUSE and openSUSE haven't i386.

But I also forgot to ask you, maybe you want armv7l, which is also 32-bit?

**Comment by pirate486743186** [comment]
i just have an old laptop.
i think that raspbian (for rasperry pi) is actually 32bit.

but it really doesn't matter. It would require too much effort for very little actual use.

**Comment by hawkeye116477** [comment]
> i think that raspbian (for rasperry pi) is actually 32bit.

Ok, so I was right, it's arm architecture. 

> It would require too much effort for very little actual use.

Yeah, I already tried in the past compiling for arm and then checking it on emulator and I had problems with both Current and Classic.
