### ISSUE TITLE
Waterfox AppImage does not work on KDE neon

### ISSUE THREAD

**Issue by lo9-u** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#35]
Hello,

I have loaded the current KDE neon user edition ISO file (27 August 2020) and this Waterfox Classic AppImage file.

https://build.opensuse.org/package/binary/download/home:hawkeye116477:waterfox/waterfox-classic-appimage/AppImage/x86_64/waterfox-classic-2020.08.1-88.2.Build88.3.glibc2.17-x86_64.AppImage

But when I open the Waterfox Classic AppImage file on KDE neon nothing happens, no Waterfox Classic appears.

Is this a bug in KDE neon or in the AppImage file? I have not configured anything and only used the default setting of KDE neon.

Can you help?

**Comment by hawkeye116477** [comment]
@lo9-u What happens when you open it from console? What message appears?

**Comment by lo9-u** [comment]
@hawkeye116477 

XPCOMGlueLoad error for file /tmp/.mount_waterfe3c13d/usr/bin/libxul.so:
libstartup-notification-1.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

**Comment by hawkeye116477** [comment]
@lo9-u Try `sudo apt install libstartup-notification0`.

**Comment by lo9-u** [comment]
@hawkeye116477 
It now works after the installation of libstartup-notification0

But can you fix this in the next AppImage version?

**Comment by hawkeye116477** [comment]
No, it should be installed by user.

**Comment by hawkeye116477** [comment]
Problem should be fixed in Classic build 139.1, it's without startup notification now.
