### ISSUE TITLE
waterfox-g-kpe update error

### ISSUE THREAD

**Issue by IzzySoft** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#47]
I just applied the offered switch to `waterfox-g-kpe`. Having G3 installed, this caused an error with `dpkg`:

```
E: /tmp/apt-dpkg-install-meMhz1/4-waterfox-g-kpe_4.1.1.1-0+9.1_amd64.deb: trying to overwrite '/usr/bin/waterfox-g3', which is also in package waterfox-g3-kpe 2.7-0+130.2
```

As the package indicates v4, shouldn't that binary be `/usr/bin/waterfox-g4` instead? And what do you recommend to do with that error here (safe to ignore until fixed, or remove G3 and re-install `waterfox-g-kpe`, wait for an update on `waterfox-g-kpe` to fix it, or something else)?

Thanks in advance for a solution/fix, and special thanks for keeping Waterfox packages alive!

**Comment by IzzySoft** [comment]
OK, as that left G3 unusable, I had to decide myself:

```bash
# G3 was broken now, so:
apt remove waterfox-g3-kpe
# tried re-installing G
apt reinstall waterfox-g-kpe
# => "waterfox-g-kpe is not currently installed, so it will not be reinstalled"
apt install waterfox-g-kpe
```

Started it once, closed again, copied the G3 profile to the new name, seems to work so far. Still wonder what went wrong, as the G package states

    Replaces: waterfox-g3-kpe (<< 2.7-0~), waterfox-g4-kpe (<< 1.1-0~)

I had 2.7.0 installed, so it should have been replaced cleanly (or what does `<<` mean?)…

**Comment by hawkeye116477** [comment]
Ah, my bad, version number in replaces should be little higher.

**Comment by IzzySoft** [comment]
> Ah, my bad, version number in replaces should be little higher.

Happens – thanks for fixing! So I can recommend my family to upgrade now.

> Main binary is `waterfox-g`, there are also backwards compatibility symlinks for convenience.

Yes, which is what raised the conflict. I had hoped to try your suggested "parallel install", which was made impossible this way (no problem, G4 works fine now after I also updated my userChrome stuff). Do you know if TMP should still work like with G3, via userChromeJS? I never found the time to try that out on G3.
