### ISSUE TITLE
Gahcrashing on Amazon (and other sites)

### ISSUE THREAD

**Issue by RJVB** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#48]
Waterfox tabs have been crashing A LOT for me lately, today I could hardly check out an Amazon product page, e.g.

https://www.amazon.fr/Otoscope-Nettoyeur-Nettoyage-Compatible-Domestiques/dp/B09PYPFX1D

it would start to load and then crash when (almost) done, or when I started scrolling.

I can't use the official build because my glibc is just too old so I can't check whether it's an issue with that build too (and report it there....)

**Comment by hawkeye116477** [comment]
I don't think that's related with my build, I'm not making that much changes :smile:. 
Anyway, what's your Waterfox and distro version?

**Comment by RJVB** [comment]
I also think it's more likely to be an issue with Waterfox itself, and unlikely to be an issue with my libc. I'm on an Ubuntu 14.04 clone with quite a few self-updated libraries. Waterfox is the latest build you provide, 4.1.0 IIRC. I think I saw that's 2 point releases behind, is that possible?

**Comment by hawkeye116477** [comment]
Well, newest Waterfox G version is 4.1.2, so maybe try updating it (package name changed to waterfox-g-kpe). 
Anyway, maybe your issues are somehow related with your very old distro (drivers?).

**Comment by RJVB** [comment]
On Friday May 13 2022 12:35:12 hawkeye116477 wrote:
>Well, newest Waterfox G version is 4.1.2, so maybe try updating it (package name changed to waterfox-g-kpe). 

I'm not seeing that in the AppImage list? And is that "kpe" or "kde" ?!

>Anyway, maybe your issues are somehow related with your very old distro (drivers?).

Goodness, if my distro is "very old", what label must by 2011 Mac deserve, or me myself :D

Anyway, no, I don't think the issue is with my distro or drivers; other browsers including Firefox itself don't show the crashing as far as I can tell. Kernel, X server, Mesa, the userland Intel graphics stuff, gtk3 have all been updated to far newer versions than what came with the system. It's also my understanding that e.g. the graphics drivers run in the "host" process, and so if something crashes there the entire browser comes down. 
I managed to prevent the issue on the linked page by blacklisting amazon in a few of my extensions that aren't useful there anyway, but I keep getting crashed tabs when I purchase something, just after the gaudy payment processing page.

Anyway, I wasn't hoping for more from you than providing the latest WF version, and possibly some pointers how to get more useful information than "Gah, tab crashed".

**Comment by hawkeye116477** [comment]
> possibly some pointers how to get more useful information than "Gah, tab crashed".

Try running it from terminal/console and see what message says.

> I'm not seeing that in the AppImage list? And is that "kpe" or "kde" ?!

Oh, mistake, KPE/KDE and new package name doesn't apply to AppImage. Newest version is on same site as always :smile:.

**Comment by RJVB** [comment]
>Try running it from terminal/console and see what message says.
Doh, yes, I could have look in my startkde.log file... Next time! :)

>Oh, mistake, KPE/KDE and new package name doesn't apply to AppImage. Newest version is on same site as always :smile:.

It is now, yep. Thanks, that was quick!

**Comment by RJVB** [comment]
>Try running it from terminal/console and see what message says.

Nothing! :(
