### ISSUE TITLE
waterfox-g-kpe pre-packaged for Fedora 36?

### ISSUE THREAD

**Issue by d-albrecht** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#49]
Hey,
any reason why Waterfox G isn't pre-packaged for the current (and rolling/testing ("Rawhide") for that matter) Fedora release?
What consequences would using the Fedora35 repo have (or in other words: what is the difference between the packages for different releases of the same distro)?

**Comment by hawkeye116477** [comment]
> any reason why Waterfox G isn't pre-packaged for the current (and rolling/testing ("Rawhide") for that matter

There is build error on that distros. I'm not sure what's wrong, I'll look into this soon.

**Comment by hawkeye116477** [comment]
It's partially fixed now. However it's without additional optimizations - no PGO+LTO, cuz I have no idea how to fix that. Maybe it works for GCC (but GCC requires more resources, so not sute if that will be possible on OBS), but apparently with Clang there are errors.

**Comment by d-albrecht** [comment]
I will sure give it a try. Because what I experienced today was borderline unbearable.
For some context, I used to run LMDE 4 but with the upgrade to LMDE 5 my system bugs out quite a lot and the package selection from Debian is feeling more and more TOO "stable" (too old) for my taste, so I'm in the process of reinstalling my system and I might switch completely to Fedora (because I recently heard a lot of good reasons to give Fedora a try, perhaps even their SIlverblue projecct).
So, to not confuse the package manager on Fedora more than necessary, I installed both Waterfoxes from the 35 repo (which, to be fair, you said might not be as smooth). Today I tried to watch the newest LTT WAN show VOD (in case you wanted to reproduce the situation). Fresh install of Fedora Workspace Cinnamon Spin (yes, I will take this aspect of LMDE with me if I can), all system updates applied, with a fresh Waterfox G install (both the Wayland launcher and the x11 launcher). And whenever I clicked on the video from any page (channel's videos list, or search results, etc), the tab crashed and asked me whether I wanted to restore it. No of my attempts to fix this helped: enabling the browser's H264 plug-in, installing all media codecs, digging a bit in the settings. Every time I tried to load the video, the tab crashed immediately without even really loading it. Even if I "just" tried to hover over the video from the search results (when YouTube shows you a slideshow of some still images) the tab crashed. When I once rebooted the system (to see if the media codecs might not be there until I rebooted), I had a dozen kernel crashes in my log notification. So, whatever happened must have caused the kernel to skip a beat, making the browser lose the tab or whatever.
Clearly, I'm not knowledgeable enough to compile a browser myself and don't know what is necessary to do so, otherwise I probably would have done it instead of asking here, but you might still want to look into this phenomenon. Because to me it seems that it should rarely be a problem to use a package compiled for an older version of an operating system. Isn't that - more or less - the core idea of most system-agnostic package formats (flatpak, snap, appimage) Or is it that common that other libraries you rely on lose functionality with newer versions?
Either way I will report back in the next days, whether the F36 versions work for me. Did't have time for that up until today, sadly.

**Comment by hawkeye116477** [comment]
For playing videos try installing libavcodec-free. I will add that as a depend in next update.

**Comment by d-albrecht** [comment]
Given that your last update was 10 hours ago, I should have used the new build. I just tested it about an hour ago and from what I can tell based on a quick test, everything works fine so far. If other problems arise, I will report back.

Thanks for the quick response and providing those packages. I will close this issue now that - at least for me - the core issue (that there were no F36 packages) is resolved. I hope this doesn't interfere with any of your personal bookkeeping.
Have a great week.
