### ISSUE TITLE
repo error repomd.xml not found on dnf upgrade

### ISSUE THREAD

**Issue by ToddAndMargo** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#50]
Fedora36
home:hawkeye116477:waterfox.repo

# dnf upgrade
Waterfox (deb/pkg.tar.xz/rpm/AppImage) (Fed 969  B/s | 1.1 kB     00:01    
Errors during downloading metadata for repository 'home_hawkeye116477_waterfox':
  - Status code: 404 for https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/Fedora_33/repodata/repomd.xml (IP: 195.135.221.134)
Error: Failed to download metadata for repo 'home_hawkeye116477_waterfox': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

/etc/yum.repos.d/home:hawkeye116477:waterfox.repo:
[home_hawkeye116477_waterfox]
name=Waterfox (deb/pkg.tar.xz/rpm/AppImage) (Fedora_33)
type=rpm-md
baseurl=https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/Fedora_33/
gpgcheck=1
gpgkey=https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/Fedora_33/repodata/repomd.xml.key
enabled=1

**Comment by hawkeye116477** [comment]
In first line you wrote Fedora 36, but in next line it tries to download metadata from Fedora 33 repo.
Repo for Fedora 33 was removed.

**Comment by ToddAndMargo** [comment]
Would you spin a 36 repo?

I don't suppose there is an agnostic repo?

**Comment by hawkeye116477** [comment]
`dnf config-manager --add-repo https://download.opensuse.org/repositories/home:hawkeye116477:waterfox/Fedora_36/home:hawkeye116477:waterfox.repo`

**Comment by ToddAndMargo** [comment]
Awesome!
