### ISSUE TITLE
cannot update/install extensions?!

### ISSUE THREAD

**Issue by RJVB** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#54]
I'm running the AppImage Waterfox G4 build, which I unpack via the `--appimage-extract` option to get faster startup speed.

For a while now (since at least autumn last year) I have not been able to update or install extensions. Automatic updates fail without error, but installing a new one tells me that the failure is due to Waterfox not being able to modify a file.

I need to quit Waterfox, and start Firefox using the same profile to complete the operation.

I cannot use the official WF builds because they require a newer libc than the one I have.

**Comment by hawkeye116477** [comment]
I checked and everything is fine. Maybe try newest version.

**Comment by RJVB** [comment]
>I checked and everything is fine. Maybe try newest version.

Thanks for the heads-up that there might be a new version. I'm not holding my breath though; I noticed that another one of my browsers (slimjet) shows exactly the same behaviour. It's quite exasperating that I have no idea how to debug this...

**Comment by RJVB** [comment]
bump

I've started noticing the same issue with a chrome-based browser, and in Firefox (Dev. Ed.) itself. When that happened I had to (could, fortunately) install the extension into a different profile, and then do the into my default profile by hand (browser not running).
