### ISSUE TITLE
Waterfox is out of date

### ISSUE THREAD

**Issue by nijahplays** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#56]
Waterfox reports that it is in version G4.1.4

**Comment by nijahplays** [comment]
![image](https://user-images.githubusercontent.com/70035007/190564549-19a17192-a9ad-472c-ba9f-505b844e4365.png)

**Comment by hawkeye116477** [comment]
What distribution are you using?

**Comment by nijahplays** [comment]
At the time of posting it was a Fedora 36 installation with nothing changed

**Comment by hawkeye116477** [comment]
Please check for updates again.
