### ISSUE TITLE
[Crash Report] Waterfox 4.1.5 (Arch (btw)) frequent tab crashes.

### ISSUE THREAD

**Issue by DonielMoins** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#57]
This frequently happens for seemingly no reason. Sometimes it's tabs crashing en masse, other times it's the whole browser crashing.
[These (Journald) logs](https://pst.klgrth.io/paste/qev55) are from one tab crashing.

![image](https://user-images.githubusercontent.com/8723803/190634103-3f3ebc25-5b46-4a14-bdfd-1ce5748b8a7a.png)

![image](https://user-images.githubusercontent.com/8723803/190634492-d651369e-67e2-4630-ada1-820d300e1aad.png)

As of posting this, my Waterfox is the latest pre-built version (from your repo).
And this is my 3rd install without any change.

EDIT 1: This also happened on my KDE Plasma install. And my Nvidia driver is the nvidia-open package. Everything is up-to-date.

**Comment by hawkeye116477** [comment]
Well, as I sad also on #48, I don't think that's related with my build, I'm not making that much changes.
Anyway, you can also check https://aur.archlinux.org/packages/waterfox-g4-bin for comparison.
