### ISSUE TITLE
Appimage won't keep localisation settings

### ISSUE THREAD

**Issue by M-Rick** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#62]
I downloaded the Appimage of Waterfox G5. I wanted to set it to use French. I got access to all the language settings and I could choose any of them.
But after relaunching Waterfox, the application always restarts in English.
I have discovered that after every new launch, Waterfox duplicates its settings folder but without keeping the settings such as the locale, but it keeps the themes.
For instance, Waterfox should be able to detect itself witch localisation to use as well like the other Appimages.

![Capture d’écran de 2023-01-01 20-50-04](https://user-images.githubusercontent.com/2520948/210224877-a3a01d29-42bf-43a3-a268-73f1d8b75ddc.png)

**Comment by hawkeye116477** [comment]
If you will extract AppImage, then it should work correctly. I haven't other idea how to fix that for now.
