### ISSUE TITLE
WF Appimage version crashing shortly after startup

### ISSUE THREAD

**Issue by jelabarre59** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#66]
At some point this evening Waterfox started truing to update it's Appimage file.  At first it was saying it needed to restart to complete the install.  After that when I would re-open the tabs I had open before, within a minute or so it would again say it needed to restart for an update.

It continued on this cycle of start and then reset until I decided to stop trying to start it.  I downloaded the latest AppImage from here in Firefox and directly ran the newer version (waterfox-g-5.1.3-35.1.Build36.1.glibc2.17-x86_64_90a779f70742ba1a7ac68713de2a10a7.AppImage).  That version crashes within a minute of bringing it up and loading web pages (or even opening my Bitwarden extension).  The only way to keep it running longer is to start it up and not load anything.

### Running G5.1.3-35 from command line I get this output:

/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
console.debug: "Applying chrome://browser/content/overlays/tabfeatures.xhtml to chrome://browser/content/browser.xhtml"
console.debug: "Applying chrome://browser/content/overlays/privatetab.xhtml to chrome://browser/content/browser.xhtml"
console.debug: "Applying chrome://browser/content/overlays/statusbar.xhtml to chrome://browser/content/browser.xhtml"
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D (t=1.89849) [GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D
JavaScript error: moz-extension://dd9c4463-66e3-4cb9-97e4-fa9000931320/utils.js, line 184: TypeError: Array.slice is not a function
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Receive IPC close with reason=AbnormalShutdown (t=60.3575) Exiting due to channel error.
/tmp/.mount_waterfrxaLqF/AppRun: line 7: 632978 Bus error               (core dumped) "$HERE/usr/bin/waterfox-g" "$@"

### Running the previous version (waterfox-g-latest-x86_64_0c45c55b0e59a0d04554228e34f5c47e.AppImage) runs slightly longer, but the individual tabs crash until eventually the entire browser crashes:

ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
console.debug: "Applying chrome://browser/content/overlays/tabfeatures.xhtml to chrome://browser/content/browser.xhtml"
console.debug: "Applying chrome://browser/content/overlays/privatetab.xhtml to chrome://browser/content/browser.xhtml"
console.debug: "Applying chrome://browser/content/overlays/statusbar.xhtml to chrome://browser/content/browser.xhtml"
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D (t=1.85538) [GFX1-]: Unrecognized feature ACCELERATED_CANVAS2D
JavaScript error: moz-extension://dd9c4463-66e3-4cb9-97e4-fa9000931320/utils.js, line 184: TypeError: Array.slice is not a function
JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory.
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "moz-extension://08086203-d5d4-4923-ab54-2ef1cfeb9497"
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "moz-extension://08086203-d5d4-4923-ab54-2ef1cfeb9497"
JavaScript error: resource://gre/modules/LoginManagerParent.jsm, line 136: TypeError: gRecipeManager is null
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "moz-extension://08086203-d5d4-4923-ab54-2ef1cfeb9497"
JavaScript error: resource://gre/modules/LoginManagerParent.jsm, line 136: TypeError: gRecipeManager is null
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://www.dwservice.net"
JavaScript error: resource://gre/modules/LoginManagerParent.jsm, line 136: TypeError: gRecipeManager is null
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://www.dwservice.net"
JavaScript error: resource://gre/modules/LoginManagerParent.jsm, line 136: TypeError: gRecipeManager is null
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://www.dwservice.net"
JavaScript error: resource://gre/modules/LoginManagerParent.jsm, line 136: TypeError: gRecipeManager is null
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://www.dwservice.net"
JavaScript error: resource://gre/modules/LoginManagerParent.jsm, line 136: TypeError: gRecipeManager is null
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://www.dwservice.net"
JavaScript error: resource://gre/modules/LoginManagerParent.jsm, line 136: TypeError: gRecipeManager is null
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://www.dwservice.net"
JavaScript error: resource://gre/modules/LoginManagerParent.jsm, line 136: TypeError: gRecipeManager is null
JavaScript error: https://www.dwservice.net/session.dw, line 1: TypeError: right-hand side of 'in' should be an object, got null
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://www.dwservice.net"
JavaScript error: resource://gre/modules/LoginManagerParent.jsm, line 136: TypeError: gRecipeManager is null
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://www.dwservice.net"
JavaScript error: resource://gre/modules/LoginManagerParent.jsm, line 136: TypeError: gRecipeManager is null
console.warn: LoginRecipes: "getRecipes: falling back to a synchronous message for:" "https://www.dwservice.net"
JavaScript error: resource://gre/modules/LoginManagerParent.jsm, line 136: TypeError: gRecipeManager is null
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
/tmp/.mount_waterfBKQvee/AppRun: line 7: 635664 Bus error               (core dumped) "$HERE/usr/bin/waterfox-g" "$@"

### That's about it for any error information I can get from it right now.

**Comment by hawkeye116477** [comment]
Hmm, it works fine for me. I suppose that could be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1777849. What's your distro?

Try setting `gfx.x11-egl.force-enabled` to `true` and `gfx.canvas.accelerated` to `false`.

**Comment by jelabarre59** [comment]
This can be closed (at least from my viewpoint) as I'm running from the TAR file now.

**Comment by hawkeye116477** [comment]
There is not much difference compared with official TAR, so if it's fine with official, then should work fine with AppImage too.
