### ISSUE TITLE
Please add a Snap package

### ISSUE THREAD

**Issue by lproven** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#68]
Waterfox is especially useful on Ubuntu, because it integrates with the Unity menu bar. Firefox, LibreWolf etc. no not support this any more.

I regularly have problems with the PPA and `.deb` packages.

For instance:

* it looks like you don't have a package or repo for 23.04 yet. 

* The 22.04 .deb has the same name as the 22.10 .deb but the latter won't install on the former.

* The changed GPG key filename problem I reported earlier.

A Snap would be very helpful and would resolve these issues.

A Flatpak would too but as a now official Flavour, Ubuntu Unity is no longer allowed to include Flatpak support. :-(

Thanks for a handy build!

**Comment by hawkeye116477** [comment]
> it looks like you don't have a package or repo for 23.04 yet.
 
Thanks for report. I'll add it soon.

There is already AppImage package. I'm not planning more container packages for Waterfox, maybe ask @YamiYukiSenpai about that, who experimented with it. 
Honestly generally I'm against of container packages, cuz usually they're bigger, have problems with integration with themes and works slower. Other packages than AppImage also requires packaging additional depends with them and that can be problemating from license side.

**Comment by lproven** [comment]
OK, fair points! Thanks for the response.

**Comment by hockeymikey** [comment]
@hawkeye116477 What did you switch to? I'm on Librewolf myself. Also don't close the repos, they are essential for others and should be kept up. Always happy to help if needed.

**Comment by lproven** [comment]
> @hawkeye116477 What did you switch to?

They implied to Floorp. I must try it, but I'm happy with Waterfox.

> I'm on Librewolf myself. 

Tried it. Don't see anything much for me there and I think it doesn't work with Unity's menus.

> Also don't close the repos, they are essential for others and should be kept up. Always happy to help if needed.

:100:% agreed.

**Comment by lproven** [comment]
> owever maybe I'll create repos for Floorp (other packages than deb, which already exists), which looks as better maintaned browser now.

As you say -- there is a PPA. I just tried it. Nice default setup with vertical tabs, but the deal breaker for me is that it's broken in the same way as upstream Firefox: Gtk menu bars don't work. So it can't use the Unity global menu bar.

That largely rules it out for me, I'm afraid.
