### ISSUE TITLE
Unmet dependencies in .debs

### ISSUE THREAD

**Issue by philclifford** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#69]
The direct downloads for recent Ubuntus (kinetic) appear to depend on unavailable packages, and this also applies if I add the repo.

```
The following packages have unmet dependencies.
 waterfox-g-kde : Depends: kwaterfoxhelper but it is not installable
```

The direct download is more needy and no more successful

```
The following packages have unmet dependencies.
 waterfox-g-kde : Depends: waterfox-g but it is not installable
                  Depends: kwaterfoxhelper but it is not installable
```

**Comment by hawkeye116477** [comment]
Thanks for report. Package kwaterfoxhelper is now available for Kinetic, so should be fixed.

**Comment by philclifford** [comment]
Thanks.  Because I prefer not to fully trust any signing keys on principle I followed the following pattern,  which I recommend (and also because of `deb-get`)

``` 
cat /etc/apt/sources.list.d/waterfox.list 
deb [signed-by=/usr/share/keyrings/waterfox-archive-keyring.gpg] https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_22.10/ /
```
 
Installed fine so closing this.  Are you planning to support Lunar (23.04) soon ?
Thanks again.
