### ISSUE TITLE
Waterfox not recognised as a media player

### ISSUE THREAD

**Issue by tatokis** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#74]
Waterfox G supports [MPRIS](https://specifications.freedesktop.org/mpris-spec/latest/) on Linux for external media control.

I have `waterfox-g-kpe` installed on Ubuntu 20.04, and my system does not recognise it as a valid media player. This is because Waterfox claims that there should be a `waterfox.desktop` file, as the `DesktopEntry` property in `org.mpris.MediaPlayer2` is simply `waterfox`, even though the one shipped with the package is `waterfox-g.desktop`.

![d-feet](https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/assets/6003656/cebf9c4f-0189-4b4e-ba8d-19b1a1961d0b)

As a workaround, a symlink fixes this, but obviously creates a duplicate entry.

```
$ ln -s /usr/share/applications/waterfox-g.desktop ~/.local/share/applications/waterfox.desktop
```

I assume this is not an upstream issue, as the prebuilt archive from waterfox.net does not contain a `.desktop` file and the binary there is simply called `waterfox`.

**Comment by tatokis** [comment]
```
$ ls /usr/share/applications/waterfox.desktop
ls: cannot access '/usr/share/applications/waterfox.desktop': No such file or directory
$ dbus-send --print-reply --dest=org.mpris.MediaPlayer2.firefox.instance3472 /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2 string:DesktopEntry
method return time=1705204093.080082 sender=:1.141 -> destination=:1.1055 serial=1986 reply_serial=2
   variant       string "waterfox"
```

**Comment by hawkeye116477** [comment]
Looks like problem might be at https://github.com/WaterfoxCo/Waterfox/blob/f1dd94c050a1cf4e62c4142785755f626e95441f/widget/gtk/MPRISServiceHandler.cpp#L364C25-L364C38. I'm setting `ac_add_options --with-app-name=waterfox-g
ac_add_options --with-app-basename=Waterfox` and I assume that probably it takes desktop file name from basename.
However it was named as Waterfox G to distinguish from Classic edition, but now only one edition is updated, so I'll change it to just waterfox, so it will be fixed.

**Comment by tatokis** [comment]
While this issue is fixed, this update has caused a few issues.

I had waterfox-g-kpe installed previously, and it upgraded me to the waterfox-g-kde package. While that's perfectly fine on its own, the upgrade failed with:
```
Preparing to unpack .../29-waterfox-kde_6.0.8-0+7.1_amd64.deb ...
Unpacking waterfox-kde (6.0.8-0+7.1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-pQ54Cw/29-waterfox-kde_6.0.8-0+7.1_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/waterfox-g', which is also in package waterfox-g-kpe 6.0.7-0+232.1
Selecting previously unselected package waterfox-i18n-en-gb.
Preparing to unpack .../30-waterfox-i18n-en-gb_6.0.8-0+7.1_all.deb ...
Unpacking waterfox-i18n-en-gb (6.0.8-0+7.1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-pQ54Cw/30-waterfox-i18n-en-gb_6.0.8-0+7.1_all.deb (--unpack):
 trying to overwrite '/usr/lib/waterfox-g/browser/extensions/langpack-en-GB@l10n.waterfox.net.xpi', which is also in package waterfox-g-i18n-en-gb 6.0.7-0+232.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Preparing to unpack .../31-waterfox-g-i18n-en-gb_6.0.8-0+7.1_all.deb ...
Unpacking waterfox-g-i18n-en-gb (6.0.8-0+7.1) over (6.0.7-0+232.1) ...
Preparing to unpack .../32-waterfox-g-kpe_6.0.8-0+7.1_all.deb ...
Unpacking waterfox-g-kpe (6.0.8-0+7.1) over (6.0.7-0+232.1) ...
dpkg: προειδοποίηση: unable to delete old directory '/etc/waterfox-g': Directory not empty
Errors were encountered while processing:
 /tmp/apt-dpkg-install-pQ54Cw/29-waterfox-kde_6.0.8-0+7.1_amd64.deb
 /tmp/apt-dpkg-install-pQ54Cw/30-waterfox-i18n-en-gb_6.0.8-0+7.1_all.deb
```

and  on another machine

```
Log started: 2024-01-29  9:32:20
Selecting previously unselected package waterfox-kde.
(Reading database ... ^M(Reading database ... 5%^M(Reading database ... 10%^M(Reading database ... 15%^M(Reading database ... 20%^M(Reading database ... 25%^>
Preparing to unpack .../waterfox-kde_6.0.8-0+7.1_amd64.deb ...
Unpacking waterfox-kde (6.0.8-0+7.1) ...
dpkg: error processing archive /var/cache/apt/archives/waterfox-kde_6.0.8-0+7.1_amd64.deb (--unpack):
 trying to overwrite '/usr/bin/waterfox-g', which is also in package waterfox-g-kpe 6.0.7-0+232.1
Preparing to unpack .../waterfox-g-kpe_6.0.8-0+7.1_all.deb ...
Unpacking waterfox-g-kpe (6.0.8-0+7.1) over (6.0.7-0+232.1) ...
dpkg: warning: unable to delete old directory '/etc/waterfox-g': Directory not empty
Errors were encountered while processing:
 /var/cache/apt/archives/waterfox-kde_6.0.8-0+7.1_amd64.deb
Log ended: 2024-01-29  9:32:23
```

Running `sudo apt -f install` without doing anything else fixes it.

And then after that, unfortunately Waterfox starts with a new profile. You have to run `waterfox -P` in a terminal and select the correct one again.
