### ISSUE TITLE
waterfox-kde removes classic?

### ISSUE THREAD

**Issue by IzzySoft** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#77]
I use your packages for Ubuntu here on my Mint machines. Now the package manager advised me to update to `waterfox-kde` – but then showed the update would remove Waterfox Classic:

![image](https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/assets/6781438/b33b960c-2ae8-43d9-ae38-b692a4903c49)

I need both, so removing classic is what I want to avoid. I have no clue what is causing that, as the package itself (`apt show waterfox-kde`) doesn't even mention classic:

```
$ apt show waterfox-kde
Package: waterfox-kde
Version: 6.0.8-0+11.1
Priority: optional
Section: web
Maintainer: hawkeye116477 <hawkeye116477@gmail.com>
Installed-Size: 259 MB
Provides: gnome-www-browser, waterfox-g, www-browser
Depends: libasound2 (>= 1.1.0), libatk1.0-0 (>= 1.12.4), libc6 (>= 2.30), libcairo-gobject2 (>= 1.10.0), libcairo2 (>= 1.10.0), libdbus-1-3 (>= 1.9.14), libdbus-glib-1-2 (>= 0.78), libfontconfig1 (>= 2.12.6), libfreetype6 (>= 2.3.5), libgcc-s1 (>= 4.2), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.37.0), libgtk-3-0 (>= 3.13.7), libharfbuzz0b (>= 0.6.0), libpango-1.0-0 (>= 1.22.0), libpangocairo-1.0-0 (>= 1.14.0), libstdc++6 (>= 9), libx11-6, libx11-xcb1 (>= 2:1.6.9), libxcb-shm0, libxcb1, libxcomposite1 (>= 1:0.4.5), libxcursor1 (>> 1.1.2), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxi6, libxrandr2 (>= 2:1.4.0), libxrender1, libxtst6
Suggests: fonts-lyx, pulseaudio, kwaterfoxhelper, waterfox-g-wayland, ffmpeg
Breaks: waterfox-g-kpe (<< 6.0.7-0+), waterfox-g3-kpe (<< 4.1.1-0+), waterfox-g4-kpe (<< 4.1.1-0+)
Replaces: waterfox-g-kpe (<< 6.0.7-0+), waterfox-g3-kpe (<< 4.1.1-0+), waterfox-g4-kpe (<< 4.1.1-0+)
Homepage: https://www.waterfox.net/
Download-Size: 69,5 MB
APT-Sources: http://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/xUbuntu_20.04  Packages
Description: Customizable privacy-conscious web browser with primary support for webextensions and better integration with KDE
```

Classic is neither mentioned in `Breaks` nor in `Replaces`. Any idea what might be going on there – and how to make sure Classic is **not** uninstalled on this upgrade? Thanks in advance!

**Comment by hawkeye116477** [comment]
Classic had `waterfox-kde` as Replaces and Breaks and that's why you might see that now. 
Maybe I'll see if something can be done with that. However I think that you shouldn't be using Classic now, cuz it's without upstream updates almost 2 years.

**Comment by IzzySoft** [comment]
> Maybe I'll see if something can be done with that.

That'll be nice, thanks!

> However I think that you shouldn't be using Classic now

My main driver there is G of course. But I still need/prefer Classic for some places. Fewer now than 2..3 years ago, but still (also as some XUL addons are no longer available with G – or can all of them be loaded there now? I was really happy to see e.g. Tab Mix Plus return with all its features, but have my doubts other older XUL addons would work there "out of the box". And I'm pretty much used to Waterfox :blush:

> Pale Moon or Basilisk

Might be options, yes. But not the same. I'd probably get used to those – but currently my other projects (check for "IzzyOnDroid") don't leave me much time to configure everything anew. Not to speak of $dayjob and RL…

Thanks a lot for all your help! I'm really glad you keep the `*.deb`s coming for WF-G. And surely I cannot expect you keeping Classic updated forever. One day I'll have to switch that one out I guess…

**Comment by IzzySoft** [comment]
That conflict is gone now, thanks – but updating G from 6.0.7 to 6.0.8 entirely broke the package:

![image](https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/assets/6781438/e912aecc-9619-45c7-94e2-8de44e6d69c7)

![image](https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/assets/6781438/d6e71e44-eb23-4e3e-b2e0-981861452573)

Luckily I was able to grab the 6.0.7 `*.deb` and install that manually to get it back working.

Going by the error message that's not related to Classic, but to the change of the package name somehow: `waterfox-kde_6.0.8` vs. `waterfox-g-kpe_6.0.7`. No idea why this happens. Maybe something amiss in the "Replaces" section?

    Replaces: waterfox-g-kpe (<< 6.0.7-0+), waterfox-g3-kpe (<< 4.1.1-0+), waterfox-g4-kpe (<< 4.1.1-0+)

is the `<< 6.0.7-0+` read as "before 6.0.7-0"? Then that might explain. If it's rather "≤ 6.0.7.0" I have no idea…

**Comment by hawkeye116477** [comment]
Oh, yeah, it should be `<=` instead of  `<<`, my bad.

**Comment by IzzySoft** [comment]
:hankey: happens… Waiting for `>= +11.2` then before I try updating again :wink:

**Comment by hawkeye116477** [comment]
+24.1 is available now.

**Comment by IzzySoft** [comment]
Just saw it, thanks! Will check "later today" (currently busy at $dayjob). Not that I expect any problems, but I have some tasks still open in tabs which I first need to finish.

PS: The trouble yesterday had one positive aspect, though: Once I manually installed the DEB of the previous release (`dpkg -i`), all windows and tabs restored fine. So now I'm sure that works for multiple windows as well – which I never dared trying before :zany_face:

I've marked the notification in my inbox so I don't forget to report back here and close the issue.

**Comment by IzzySoft** [comment]
Sorry to disappoint you, but I just had the very same trouble again:

![image](https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/assets/6781438/20cbc83a-f414-41fa-8411-bb1eee2ce8d2)

![image](https://github.com/hawkeye116477/waterfox-deb-rpm-arch-AppImage/assets/6781438/839f32d4-9bed-45ac-8f9b-87558426b84f)

    Replaces: waterfox-g-kpe (<= 6.0.7-0+), waterfox-g3-kpe (<= 4.1.1-0+), waterfox-g4-kpe (<= 4.1.1-0+)

Hm. Maybe it considers `6.0.7-0+232.1 > 6.0.7-0+`? Maybe make it `< 6.0.8-0+`?

**Comment by hawkeye116477** [comment]
Hmm, maybe, docs didn't say about that unfortunately. However looks like I could do also  `<< ${source:Version}` and maybe that will be even better.

**Comment by IzzySoft** [comment]
As my remedy (`dpkg -i` the `6.0.7`) seems to be reliable, I gladly test for you. This time I was fast enough, so the browser kept running. Only the desktop icon got confused for a few seconds :see_no_evil:

Btw: Got reports from others who "fell into this trap". One said "I used Synaptics to install it again, that worked. All my addons etc were kept." So should someone else ask for a quick remediation, that's worth a try. A "clean update" is of course preferable :wink:

**Comment by IzzySoft** [comment]
Thanks a ton! Yeah, this one went **absolutely** smooth :partying_face:
