### ISSUE TITLE
Waterfox needs an update

### ISSUE THREAD

**Issue by expertmanofficial** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#78]
I'm tired of Waterfox letting me know that I need to update it. I do it everytime when it asks, but looks like it's your problem, because Waterfox has a new update and the AppImage version still haven't been updated to latest.

Please, fix this, because Firefox's latest version includes some privacy-focused related features.

Here is the link where I always go to update:

https://download.opensuse.org/repositories/home:/hawkeye116477:/waterfox/AppImage/waterfox-g-6.0.7-68.4.Build68.10.glibc2.17-x86_64.AppImage?mirrorlist=1

**Comment by hawkeye116477** [comment]
Ah, looks like it was built, but not published. I enabled publish flag now, so it should appear after sometime.
