### ISSUE TITLE
Final Step Fail

### ISSUE THREAD

**Issue by Mr-ranger-fan-2k23** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#83]
Whenever I do the final step, I get this "Package 'waterfox-kde' has no installation candidate" error.

**Comment by hawkeye116477** [comment]
What's your distro?

**Comment by Mr-ranger-fan-2k23** [comment]
Ubuntu

**Comment by hawkeye116477** [comment]
Did you do `sudo apt-get update`?
