### ISSUE TITLE
Please update to G6.0.20

### ISSUE THREAD

**Issue by tatokis** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#84]
Apologies for opening an issue, but it'd be really appreciated if you could bump to G6.0.20, as according to the [changelog](https://www.waterfox.net/docs/releases/G6.0.20/) it contains "Critical Security Fixes, please update as soon as possible.".

Thank you for your time.

**Comment by hawkeye116477** [comment]
Update should be available after few hours if errors won't come at https://build.opensuse.org/package/show/home:hawkeye116477:waterfox/waterfox-kde.

**Comment by tatokis** [comment]
Got the update. Cheers!
