### ISSUE TITLE
Waterfox no longer showing global menu under KDE plasma after latest update

### ISSUE THREAD

**Issue by lunelovehearn** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#87]
after updating my arch system, it asked me to replace my old waterfox-kde with waterfox-kde-full and I lost the global menu. it's a deal breaker to me, as I also can't access the classic menus for some reason. any way to fix this?

**Comment by lunelovehearn** [comment]
note that this happens under wayland when using the package from your repository. when using the appimage, it shows the gobal menu. all of this happens under wayland.

**Comment by hawkeye116477** [comment]
Well, global menu support is provided by Waterfox itself, not me.
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1419151#c56.

**Comment by lunelovehearn** [comment]
well, I thought about forcing xwayland, but no success  so far or perhaps I'm missing something.
but if you can help me to force xwayland, I'll be happy to know how to.
I could try using the other waterfox package from the AUR, I'll report back.

**Comment by lunelovehearn** [comment]
yeah I also tried the about:config settings but it doen't fix it. I'll add more info later.

**Comment by lunelovehearn** [comment]
I already tried that but it didn't work. what I just did was to switch from your waterfox package to the one on the chaotic aur and the global menu works now. that's weird tbh.

oh.. just noticed that the waterfox the chaotic aur ships has the enviroment variable set to 0, just like you said. 

another thing: it seems like waterfox launcher breaks after updating to latest version, giving "too many levels of symbolic links: waterfox" if launching it from terminal. it just doesn't launch at all from plasma menus.
you may like to check why that happens.

for now, switching to the chaotic aur waterfox/forcing xwayland fixes the issue until they finish the wayland global menu integration.

thanks hawkeye for your help.

**Comment by hawkeye116477** [comment]
> another thing: it seems like waterfox launcher breaks after updating to latest version, giving "too many levels of symbolic links: waterfox

Yeah, sorry for that. Looks like I made a small bug, when renaming, should be fixed in next rebuild :smile:.

**Comment by lunelovehearn** [comment]
yeah it was weird that after having waterfox working fine for so long, an update broke the launcher so hard that even terminal was unable to run it. 
regarding the global menu, you may like to point out the bugfix on the readme for those who need or use it.

**Comment by lunelovehearn** [comment]
btw: if wayland crashes, it will take down waterfox with it and the global menu will not show. the fix is to log out and log back in into wayland session or reboot. waterfox then will show the global menus as expected.
