### ISSUE TITLE
on Arch: /bin/waterfox as endless cyclic soft link to itself

### ISSUE THREAD

**Issue by papavlos** [hawkeye116477/waterfox-deb-rpm-arch-AppImage#88]
I am updating from `home_hawkeye116477_waterfox_Arch/waterfox` (added repo in pacman.conf) rather than from AUR, but don't know where to report it: today is the second time when the "waterfox" file in /bin links to itself instead of "/usr/lib/waterfox/waterfox". 
Please check it. 
I had to remove the existing /bin/waterfox endless-cycling link and then create it as "ln -s /usr/lib/waterfox/waterfox /bin/waterfox"

**Comment by hawkeye116477** [comment]
Sorry for problems. It's fixed now in 6.5.1-3.
